/**
 * This utility file creates a formatted text file with the user's positioning results.
 * We use a well-formatted structure to make it easy to read.
 */

import { PositioningOutput } from "../components/positioning-results";
import { FormData } from "../components/step-form";

interface DocxGeneratorOptions {
  positioningOutput: PositioningOutput;
  formData: FormData;
}

export function generateDocx({ positioningOutput, formData }: DocxGeneratorOptions): string {
  const { 
    websiteHeadline, 
    socialBio, 
    ctaPhrase, 
    ctaSubheadline, 
    summary 
  } = positioningOutput;

  // Create a nicely formatted text document
  const content = `
===============================================
             YOUR BRAND POSITIONING KIT
===============================================

Generated: ${new Date().toLocaleDateString()}

WEBSITE HEADLINE
-----------------------------------------------
${websiteHeadline}

SOCIAL MEDIA BIO
-----------------------------------------------
${socialBio}

CALL-TO-ACTION MESSAGING
-----------------------------------------------
${ctaPhrase}
${ctaSubheadline}

BRAND SUMMARY
-----------------------------------------------
${summary}

YOUR INPUTS
-----------------------------------------------
• What you do: 
  ${formData.workDescription}

• Service/offer: 
  ${formData.service}

• Transformation: 
  ${formData.transformation}

• Target audience: 
  ${formData.audience}

• Pain points: 
  ${formData.painPoints}

${formData.misunderstanding ? `• Misunderstandings: 
  ${formData.misunderstanding}
` : ''}
===============================================
Generated by PositionKit © ${new Date().getFullYear()}
===============================================
`;

  // Create a Blob from the content
  const blob = new Blob([content], { type: 'text/plain' });
  
  // Create a downloadable URL
  const url = URL.createObjectURL(blob);
  
  return url;
}

export function downloadDocx(url: string, filename: string = 'positioning-kit.txt'): void {
  // Create a temporary anchor element
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  
  // Trigger the download
  document.body.appendChild(a);
  a.click();
  
  // Clean up
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}